module app.domain.phone {
    export interface Phone {
        id:String
        name:String
        sizeAndWeight:{
            dimension:Array<String>
            weight:String
        }
        storage:{
            flash:String
            ram:String
        }
        images:Array<String>
        hardware:{
            accelerometer:Boolean
            audioJack:String
            cpu:String
            fmRadio:Boolean
            physicalKeyboard:Boolean
            usb:String
        }
        display:{
            screenResolution:String
            screenSize:String
            touchScreen:Boolean
        }
        description:String
        additionalFeatures:String
        android:{
            os:String
            ui:String
        }
        availability:Array<String>
        battery:{
            standbyTime:String
            talkTime:String
            type:String
        }
        camera:{
            features:Array<String>
            primary:String
        }
        connectivity:{
            bluetooth:String
            cell:String
            gps:Boolean
            infrared:Boolean
            wifi:String
        }
    }
}